services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=   # Set your password here
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.1
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"    # Beats input
      - "5000:5000"    # TCP input
      - "9600:9600"    # Monitoring API
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=logstash_system
      - ELASTICSEARCH_PASSWORD=
      - LS_JAVA_OPTS=-Xms512m -Xmx512m

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=                    # Generated from 'docker exec -it bin/elasticsearch-reset-password -u kibana_system' 'docker compose up --build -d'
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY= # Encryption key (required for alerting)
      - XPACK_ACTIONS_CUSTOMHOSTSETTINGS=[{"url":"https://default3af5bca2f27441089562da92f28cc9.a5.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/9dd4b843>
volumes:
  es_data:
    driver: local
